import Head from "next/head";
import Header from "../components/Header/Header";
import Wordle from "../components/Wordle/Wordle";
import { useQuery } from "@tanstack/react-query";
import axios, { AxiosResponse } from "axios";
import { useEffect, useState } from "react";
import { NextPage } from "next";
import styles from "../styles/Home.module.css";
import getRandom from "../helpers/getRandom";
import Modal from "../components/Modal/Modal";

const Home: NextPage = () => {
  const [solution, setSolution] = useState<string | null>(null);
  const [modalOpen, setModalOpen] = useState<boolean>(false);
  const { error, isLoading, data } = useQuery(["words"], () =>
    axios
      .get("http://localhost:1337/words")
      .then((res: AxiosResponse) => res.data)
  );

  useEffect(() => {
    if (data) {
      const word = getRandom(data);
      setSolution(word);
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>Wordle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        {/* {solution} */}
        {solution && <Wordle solution={solution} />}
      </main>
      <button onClick={() => setModalOpen(true)}>open</button>
      <Modal open={modalOpen} setOpen={setModalOpen}>
        <h1>Modal</h1>
      </Modal>
    </>
  );
};

export default Home;
