import Head from "next/head";
import WordleGame from "../components/WordleGame/Wordle";
import { useEffect, useState } from "react";
import { NextPage } from "next";
import styles from "../styles/Home.module.css";
import Modal from "../components/Modal/Modal";
import { gameStateEnum, IWord } from "../types/types";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Keyboard from "../components/Keyboard/Keyboard";
import { useQuery } from "@tanstack/react-query";
import axios, { AxiosResponse } from "axios";
import { IResponseWord } from "../types/types";

const Home: NextPage = () => {
  const [solution, setSolution] = useState<string | null>(null);
  const [words, setWords] = useState<IWord[]>([...Array(5)]);
  const [gameState, setGameState] = useState<gameStateEnum>(
    gameStateEnum.start
  );
  const [gameOverModalOpen, setGameOverModalOpen] = useState<boolean>(false);
  const [finishModalOpen, setFinishModalOpen] = useState<boolean>(false);

  const { error, isLoading, refetch } = useQuery<IResponseWord>(
    ["random"],
    () =>
      axios
        .get("http://localhost:5400/random")
        .then((res: AxiosResponse) => res.data),
    {
      enabled: false,
    }
  );

  const restartGame = async (): Promise<void> => {
    const result = await refetch();
    if (!result.data) return;
    setSolution(result.data.word);
    setWords([...Array(5)]);
    setFinishModalOpen(false);
    setGameOverModalOpen(false);
    setGameState(gameStateEnum.inProgress);
  };

  useEffect(() => {
    if (gameState === gameStateEnum.start) {
      restartGame();
    }
    if (gameState === gameStateEnum.finishWin) {
      setFinishModalOpen(true);
    }
    if (gameState === gameStateEnum.finishLose) {
      setGameOverModalOpen(true);
    }
  }, [gameState]);

  if (error)
    return (
      <div className={styles.info}>
        <h2 className={styles["error-text"]}>
          Oopsie! We couldn&apos;t get words for you.
        </h2>
        <p className={styles.text}>Please try again later</p>
      </div>
    );

  if (isLoading)
    return (
      <div className={styles["spinner-box"]}>
        <img src="/circle-notch-solid.svg" className={styles.spinner} />
        <p className={styles.text}>Loading</p>
      </div>
    );

  return (
    <>
      <Head>
        <title>Wordle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {gameState != gameStateEnum.start && (
          <>
            <WordleGame
              words={words}
              setWords={setWords}
              solution={solution}
              gameState={gameState}
              setGameState={setGameState}
            />
            <Keyboard words={words} />
          </>
        )}
      </main>

      {finishModalOpen && (
        <Modal setOpen={setFinishModalOpen} delay={1500}>
          <h1>Congratulations!</h1>
          <p>You solved this puzzle.</p>
          <p>One more round?</p>
          <button onClick={() => setGameState(gameStateEnum.start)}>
            New game
          </button>
        </Modal>
      )}

      {gameOverModalOpen && (
        <Modal setOpen={setFinishModalOpen} delay={1500}>
          <h1>Game Over!</h1>
          <p>Better luck next time.</p>
          <p>
            The solution is: <b>{solution}</b>
          </p>
          <p>One more round?</p>
          <button onClick={() => setGameState(gameStateEnum.start)}>
            New game
          </button>
        </Modal>
      )}
      <ToastContainer />
    </>
  );
};

export default Home;
